POST http://localhost:5000/api/user/signup
content-type: application/json

{
  "username": "alex",
  "displayName": "Alex Simp",
  "email": "alex@rip.com",
  "password": "lmao"
}

###

POST http://localhost:5000/api/user/signin
content-type: application/json

{
  "email": "akmal@rip.com",
  "password": "123"
}

###
GET http://localhost:5000/api/user

###
GET http://localhost:5000/api/user/isadmin/5f75f2024fe8392864ca5c30

