POST http://localhost:5000/api/user/signup
content-type: application/json

{
  "username": "alex",
  "displayName": "Alex Simp",
  "email": "alex@rip.com",
  "password": "lma000"
}

###

POST http://localhost:5000/api/user/signin
content-type: application/json

{
  "email": "akmal@rip.com",
  "password": "akmal123"
}

###
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWVjMjg0ZDQxNTEwMjdmNDUyMmUyNyIsImlhdCI6MTYwNjY2NTI4NSwiZXhwIjoxNjA2NzUxNjg1fQ.PhfCdodhERTJARbpn-3OtcZnvaOExNtTnET4yOzW_Zk

###
GET http://localhost:5000/api/user/isadmin/5f75f2024fe8392864ca5c30

###
GET http://localhost:5000/api/user/refreshtoken
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTM3YTUzM2ZiZjM2MTlhY2NmZTRiYSIsImlhdCI6MTYwNDU1MzAyNCwiZXhwIjoxNjM2MTEwNjI0fQ.hhWfEjFTdJCm_b22bvLemTJNfe5pL3wxNRL1he_u4yc

###
GET http://localhost:5000/api/user/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWNjMjg1Y2FiMTgzMjUwNGUyNjJiMCIsImlhdCI6MTYwNTE1OTIzMSwiZXhwIjoxNjA1MjQ1NjMxfQ.nwO8tt529h8odUskPK2Gdagy27Ph_eeWLuiulrUCuDA

###
GET http://localhost:5000/api/fleet/timeline/5faec284d4151027f4522e27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWVjMjg0ZDQxNTEwMjdmNDUyMmUyNyIsImlhdCI6MTYwNjY2NTI4NSwiZXhwIjoxNjA2NzUxNjg1fQ.PhfCdodhERTJARbpn-3OtcZnvaOExNtTnET4yOzW_Zk

###
GET http://localhost:5000/api/user/info/akmal

###
GET http://localhost:5000/api/search/recommend
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDY4ZDJkOTE3NTk4MmQ3Y2Y2M2YyZSIsImlhdCI6MTYwODM4ODAwOCwiZXhwIjoxNjA4NDc0NDA4fQ.8v8sQ4K5SmeaklJEW3L1Obq8upCqAoQ8s_E0YdzX040